# Generated by Django 3.1 on 2020-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_auto_20200827_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdata',
            name='status',
            field=models.CharField(default='In Progress', max_length=200),
        ),
    ]
